name: Build and Deploy VSTO Add-in

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
      
    - name: Restore NuGet packages
      run: nuget restore decksterity.sln
      
    - name: Create temporary certificate for signing
      shell: powershell
      run: |
        # Create self-signed certificate and store in certificate store
        $cert = New-SelfSignedCertificate -Subject "CN=Decksterity" -CertStoreLocation "Cert:\CurrentUser\My" -KeyUsage DigitalSignature -Type CodeSigning -NotAfter (Get-Date).AddYears(1)
        
        # Export to PFX without password 
        $certBytes = $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx)
        [System.IO.File]::WriteAllBytes("decksterity_TemporaryKey.pfx", $certBytes)
        
        # Update project file with certificate thumbprint
        $projectContent = Get-Content "decksterity.csproj" -Raw
        $projectContent = $projectContent -replace '<ManifestCertificateThumbprint></ManifestCertificateThumbprint>', "<ManifestCertificateThumbprint>$($cert.Thumbprint)</ManifestCertificateThumbprint>"
        Set-Content "decksterity.csproj" -Value $projectContent -NoNewline
        
        # Display certificate info
        Write-Host "Certificate created with thumbprint: $($cert.Thumbprint)"
        Write-Host "Certificate subject: $($cert.Subject)"
        Write-Host "Updated project file with thumbprint"
        
    - name: Build solution
      run: msbuild decksterity.sln /p:Configuration=Release /p:PublishUrl="https://avirut.github.io/decksterity/"
      
    - name: Publish ClickOnce application
      run: msbuild decksterity.csproj /t:Publish /p:Configuration=Release /p:PublishUrl="https://avirut.github.io/decksterity/" /p:InstallUrl="https://avirut.github.io/decksterity/"
      
    - name: Prepare deployment files
      shell: powershell
      run: |
        # Create deployment directory
        New-Item -ItemType Directory -Force -Path "deployment"
        
        # Copy published files
        Copy-Item -Path "bin\Release\app.publish\*" -Destination "deployment\" -Recurse -Force
        
        # Create index.html for user-friendly access
        @"
        <!DOCTYPE html>
        <html>
        <head>
            <title>Decksterity PowerPoint Add-in</title>
            <style>
                body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }
                .install-button { background: #0078d4; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 20px 0; }
                .install-button:hover { background: #106ebe; }
            </style>
        </head>
        <body>
            <h1>Decksterity PowerPoint Add-in</h1>
            <p>Enhance your PowerPoint presentations with visual elements and layout tools.</p>
            
            <h2>Installation</h2>
            <p>Click the button below to install or update the Decksterity add-in:</p>
            <a href="setup.exe" class="install-button">Install Decksterity</a>
            
            <h2>Features</h2>
            <ul>
                <li>Harvey Balls (progress indicators)</li>
                <li>Directional arrows</li>
                <li>Icons (check, cross, plus, minus, question, ellipsis)</li>
                <li>Stoplight indicators</li>
                <li>Advanced alignment and distribution tools</li>
            </ul>
            
            <h2>Requirements</h2>
            <ul>
                <li>Microsoft PowerPoint 2016 or later</li>
                <li>.NET Framework 4.7.2</li>
                <li>Visual Studio Tools for Office Runtime</li>
            </ul>
            
            <p><small>The add-in will automatically check for updates and install them when available.</small></p>
        </body>
        </html>
        "@ | Out-File -FilePath "deployment\index.html" -Encoding UTF8
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./deployment
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
